version: '3'

services:
  web:
    image: $CONTAINER_IMAGE
    deploy:
      restart_policy:
        condition: any
        delay: 60s
      labels:
        - traefik.frontend.rule=Host:community-dksk.demo.protracco-project.mk
        - traefik.docker.network=traefik
        - traefik.port=80
        - traefik.protocol=http
        - traefik.enable=true
        - traefik.tags=traefik
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    networks:
      - traefik
    environment:
      - REACT_APP_API_GATEWAY=https://community-dksk.demo.protracco-project.mk/
      - REACT_APP_HOST_ENV=https://community-dksk.demo.protracco-project.mk/
      - REACT_APP_LOGO=../../assets/images/dksk.png
      - REACT_APP_TITLE=title_dksk
      - REACT_APP_SUBTITLE=subtitle_dksk

networks:
  traefik:
    external: true
